name: tinyhar
dataset_name: hangtime
has_null: True
anno_json: [
  'data/hangtime/annotations/loso_sbj_0.json',
  'data/hangtime/annotations/loso_sbj_1.json',
  'data/hangtime/annotations/loso_sbj_2.json',
  'data/hangtime/annotations/loso_sbj_3.json',
  'data/hangtime/annotations/loso_sbj_4.json',
  'data/hangtime/annotations/loso_sbj_5.json',
  'data/hangtime/annotations/loso_sbj_6.json',
  'data/hangtime/annotations/loso_sbj_7.json',
  'data/hangtime/annotations/loso_sbj_8.json',
  'data/hangtime/annotations/loso_sbj_9.json',
  'data/hangtime/annotations/loso_sbj_10.json',
  'data/hangtime/annotations/loso_sbj_11.json',
  'data/hangtime/annotations/loso_sbj_12.json',
  'data/hangtime/annotations/loso_sbj_13.json',
  'data/hangtime/annotations/loso_sbj_14.json',
  'data/hangtime/annotations/loso_sbj_15.json',
  'data/hangtime/annotations/loso_sbj_16.json',
  'data/hangtime/annotations/loso_sbj_17.json',
  'data/hangtime/annotations/loso_sbj_18.json',
  'data/hangtime/annotations/loso_sbj_19.json',
  'data/hangtime/annotations/loso_sbj_20.json',
  'data/hangtime/annotations/loso_sbj_21.json',
  'data/hangtime/annotations/loso_sbj_22.json',
  'data/hangtime/annotations/loso_sbj_23.json'
]
dataset: {
  sens_folder: ./data/hangtime/raw/inertial,
  input_dim: 3,
  sampling_rate: 50,
  num_classes: 5,
  window_size: 50,
  window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  conv_kernels: 20,
  conv_layers: 4,
  conv_kernel_size: 9,
  dropout: 0.5,
  feature_extract: null,
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 100,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  train_batch_size: 100,
  test_batch_size: 1,
}