name: tinyhar
dataset_name: opportunity
has_null: True
anno_json: [
  'data/opportunity/annotations/loso_sbj_0.json',
  'data/opportunity/annotations/loso_sbj_1.json',
  'data/opportunity/annotations/loso_sbj_2.json',
  'data/opportunity/annotations/loso_sbj_3.json',
]
dataset: {
  sens_folder: ./data/opportunity/raw/inertial,
  input_dim: 113,
  sampling_rate: 30,
  num_classes: 17,
  window_size: 30,
  window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  conv_kernels: 20,
  conv_layers: 4,
  conv_kernel_size: 5,
  dropout: 0.5,
  feature_extract: null,
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 100,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  train_batch_size: 100,
  test_batch_size: 1,
}